sudo: false

addons:
  apt:
    packages:
    - libhdf5-dev

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

install:
    - pip install -e ./

script:
    - python --version
    - py.test -v -m unit -w .

after_success:
    - coveralls
    - pip uninstall -y biggie

after_failure:
    - pip uninstall -y biggie
